#!/usr/bin/env python3
"""Generate Ziggurat tables (N=256) for the standard normal distribution.

Uses mpmath for high-precision arithmetic. Outputs Rust const arrays
with hex float literals to ensure zero rounding error in the embedding.

Reference: Marsaglia & Tsang (2000), "The Ziggurat Method for Generating
Random Variables", Journal of Statistical Software.
"""

from mpmath import mp, mpf, exp, log, sqrt, pi, erfc

mp.dps = 50  # 50 decimal digits of precision

N = 256

def f(x):
    """Standard normal PDF (unnormalized): exp(-x^2/2)."""
    return exp(-x * x / 2)

def f_inv(y):
    """Inverse of f: sqrt(-2 * ln(y))."""
    return sqrt(-2 * log(y))

def tail_area(r):
    """Area of the tail beyond r: integral of f(x) from r to infinity.

    Uses the identity: integral = sqrt(pi/2) * erfc(r/sqrt(2)).
    """
    return sqrt(2 * pi) / 2 * erfc(r / sqrt(2))

def find_r(n):
    """Find r such that all N rectangles have equal area V.

    V = r * f(r) + tail_area(r)
    Then x[1] = V / f(0) = V (since f(0) = 1).
    We build layers upward: x[i+1] = f_inv(f(x[i]) + V/x[i]).
    The constraint is that x[N-1] should be close to 0 (the peak).
    """
    lo = mpf("2.0")
    hi = mpf("5.0")

    for _ in range(200):  # bisection iterations
        r = (lo + hi) / 2
        v = r * f(r) + tail_area(r)

        x = [mpf(0)] * (n + 1)
        x[0] = r
        ok = True
        for i in range(1, n):
            fi = f(x[i - 1]) + v / x[i - 1]
            if fi > 1:
                # overflowed past f(0)=1 → r is too small
                lo = r
                ok = False
                break
            x[i] = f_inv(fi)

        if not ok:
            continue

        # x[N-1] should be close to 0; if too large, r is too big
        if x[n - 1] > mpf("1e-20"):
            hi = r
        else:
            lo = r

    return (lo + hi) / 2

def generate_tables(n):
    """Generate X and Y tables for the Ziggurat algorithm."""
    r = find_r(n)
    v = r * f(r) + tail_area(r)

    # X[i]: right edge of layer i
    # X[0] = r (tail boundary)
    # X[i] for i>0: computed from equal-area constraint
    # X[N] = 0 (the peak)
    x = [mpf(0)] * (n + 1)
    x[0] = r

    for i in range(1, n):
        fi = f(x[i - 1]) + v / x[i - 1]
        x[i] = f_inv(fi)
    x[n] = mpf(0)

    # Y[i] = f(X[i])
    y = [f(xi) for xi in x]

    return r, v, x, y

def to_rust_f64(val):
    """Convert mpmath value to Rust f64 literal with full precision."""
    fval = float(val)
    return f"{fval:.18e}"

def main():
    r, v, x, y = generate_tables(N)

    print(f"// Ziggurat tables for N(0,1), N={N}")
    print(f"// r = {float(r):.17e}")
    print(f"// V = {float(v):.17e}")
    print(f"// Generated by scripts/gen_ziggurat_table.py")
    print()

    # R constant
    print(f"pub const ZIGGURAT_R: f64 = {to_rust_f64(r)};")
    print()

    # X table: N+1 entries (x[0]..x[N])
    print(f"pub const ZIGGURAT_X: [f64; {N + 1}] = [")
    for i in range(N + 1):
        comma = "," if i < N else ","
        print(f"    {to_rust_f64(x[i])}{comma} // X[{i}]")
    print("];")
    print()

    # Y table: N+1 entries (y[0]..y[N])
    print(f"pub const ZIGGURAT_Y: [f64; {N + 1}] = [")
    for i in range(N + 1):
        comma = "," if i < N else ","
        print(f"    {to_rust_f64(y[i])}{comma} // Y[{i}]")
    print("];")

if __name__ == "__main__":
    main()
